apiVersion: klot.io/v1
kind: App
metadata:
  name: speech.nandy.io
  description: Speech - Nandy I/O
spec:
  namespace: speech-nandy-io
  source:
    site: github.com
    repo: nandy-io/speech
  manifests:
  - path: daemon/kubernetes/daemon.yaml
  - path: api/kubernetes/account.yaml
  - path: api/kubernetes/api.yaml
  - path: gui/kubernetes/gui.yaml
  labels:
  - name: speakers
    description: Which nodes have speakers and you want to speak
    value: enabled
    master: false
  requires:
  - site: github.com
    repo: klot-io/redis
  url:
    protocol: http
    host: www.speech-nandy-io