apiVersion: klot.io/v1
kind: App
metadata:
  name: speech.nandy.io
spec:
  namespace: speech-nandy-io
  description: Speech - Nandy I/O
  manifests:
  - path: kubernetes/namespace.yaml
  - path: daemon/kubernetes/daemon.yaml
  - path: api/kubernetes/account.yaml
  - path: api/kubernetes/api.yaml
  - path: gui/kubernetes/gui.yaml
  settings:
  - name: speakers
    description: Which nodes have speakers and you want to speak
    multi: true
    node: enabled
  requires:
  - name: redis.klot.io
    source:
      site: github.com
      repo: klot-io/redis
  url:
    protocol: http
    host: www.speech-nandy-io