apiVersion: klot.io/v1
kind: App
metadata:
  name: speech.nandy.io
  description: Speech - Nandy I/O
spec:
  source:
    site: github.com
    repo: nandy-io/speech
  manifests:
  - path: kubernetes/namespace.yaml
  - site: github.com
    repo: nandy-io/speech-daemon
    path: kubernetes/daemon.yaml
  - site: github.com
    repo: nandy-io/speech-api
    path: kubernetes/account.yaml
  - site: github.com
    repo: nandy-io/speech-api
    path: kubernetes/daemon.yaml
  - site: github.com
    repo: nandy-io/speech-gui
    path: kubernetes/daemon.yaml
  labels:
  - name: speakers
    description: Which nodes have speakers and you want to speak
    value: enabled
    master: false
  requires:
  - site: github.com
    repo: klot-io/redis
  url:
    protocol: http
    host: www.speech-nandy-io