apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- tilt/namespace.yaml
- api/kubernetes/api.yaml
- gui/kubernetes/gui.yaml
- daemon/kubernetes/daemon.yaml
- klot-io-app.yaml
patchesStrategicMerge:
- tilt/gui.yaml
- tilt/api.yaml
- tilt/daemon.yaml
- tilt/app.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: speech-nandy-io
    name: api
  path: tilt/volumes.yaml
- target:
    group: apps
    version: v1
    kind: Deployment
    namespace: speech-nandy-io
    name: api
  path: tilt/config.yaml
