apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: speech-nandy-io
spec:
  template:
    spec:
      containers:
      - name: api
        image: api-speech-nandy-io
        imagePullPolicy: Never
        command: ["python", "-m", "ptvsd", "--host", "0.0.0.0", "--port", "5678", "/opt/service/bin/api.py"]
        readinessProbe:
          initialDelaySeconds: 20
        livenessProbe:
          initialDelaySeconds: 20
        ports:
        - name: debug
          containerPort: 5678
          protocol: TCP