apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: daemon
  namespace: speech-nandy-io
spec:
  template:
    spec:
      containers:
      - name: daemon
        image: daemon-speech-nandy-io
        imagePullPolicy: Never
        command: ["python", "-m", "ptvsd", "--host", "0.0.0.0", "--port", "5678", "/opt/service/bin/daemon.py"]
        ports:
        - name: debug
          containerPort: 5678
          protocol: TCP